version: "3"

services:
  nginx:
      image: nginx:1.15
      ports:
          - "8000:80"
      volumes:
          - .:/var/www/
          - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/nginx.conf:/etc/nginx/www.conf
      depends_on:
          - fpm
  fpm:
      build: ./docker/fpm
      volumes:
          - .:/var/www/
